### ISSUE TITLE
[Question] Istio의 Custom Resource들이 mesh logic으로 변환된 이후 적용 순서가 어떻게 보장 되는가?

### ISSUE THREAD

**Issue by ByeongHunKim** [ByeongHunKim/Cloudclub-istio-skyline#10]
**Question / 질문 내용**

**Istio의 Custom Resource들이 mesh logic으로 변환된 이후 적용 순서가 어떻게 보장 되는가?**

**Context / 상황 설명**

앞선 [Istio custom resource들이 어떻게 mesh logic으로 변하는가? #3 ](https://github.com/ByeongHunKim/cloudclub-istio-skyline/issues/3#issuecomment-2371560727_) 질문에서 **Istio의 Custom Resource들이 mesh logic으로 변환된 이후 적용 순서가 어떻게 보장 되는지?**  에 대한 추가적인 질문이 생겼습니다

**What I've Tried / 시도한 방법**
질문에 대한 답을 찾기 위해 시도해본 방법이 있다면 설명해주세요

istio의 코드를 좀 보고 이해하려고 하고 있습니다

**Resources / 관련 자료**
질문과 관련된 문서, 링크, 코드 등이 있다면 여기에 첨부해주세요

**Additional context / 추가 사항**
기타 추가적인 정보나 생각이 있다면 여기에 작성해주세요

**Comment by opp-13** [comment]
괜찮은 링크를 찾아서 공유드립니다.

https://istio-insider.mygraphql.com/en/latest/ch2-envoy/arch/listener/listener.html

https://istio-insider.mygraphql.com/en/latest/ch2-envoy/arch/network-filter/network-filter.html

**Comment by ByeongHunKim** [comment]
> 괜찮은 링크를 찾아서 공유드립니다.
> 
> https://istio-insider.mygraphql.com/en/latest/ch2-envoy/arch/listener/listener.html
> 
> https://istio-insider.mygraphql.com/en/latest/ch2-envoy/arch/network-filter/network-filter.html

@opp-13 확인해보겠습니다 감사합니다

**Comment by ByeongHunKim** [comment]
@opp-13 주신 문서를 살펴보았는데 `Istio의 Custom Resource들이 mesh logic으로 변환된 이후 적용 순서가 어떻게 보장 되는지` 알 수 있는건가요?

**Comment by opp-13** [comment]
@ByeongHunKim 
[이 링크에서 ](https://istio-insider.mygraphql.com/en/latest/ch2-envoy/arch/listener/listener.html)Example of Envoy Inbound configuration in Istio 보셔도 되긴 하는데 [이 링크의](https://istio-insider.mygraphql.com/en/latest/ch2-envoy/envoy-istio-conf-eg.html) Envoy Inbound component in Istio with logs 이미지 보시는 것이 좋을 것 같습니다.

**Comment by ByeongHunKim** [comment]
@opp-13 이미지 봤는데 숨이 턱 막히네요..ㅋㅋ

**Comment by ByeongHunKim** [comment]
어떻게 순서가 보장되는 지는 istio proxy-config 명령어로 봤을 때 처럼 LDS,RDS,CDS,EDS에 vs,dr들이 위치해있어서 순서가 보장된 것으로 이해함. 여기서 더 나아가서 envoy에서도 xDS API 컴포넌트들이 트래픽에도 관여를 하는 지 안하는 지를 issue로 등록하려 보려고 함
