### ISSUE TITLE
[Question] iptables traffic hijacking에서 iptables 몇 계층까지 처리 되는지?

### ISSUE THREAD

**Issue by opp-13** [ByeongHunKim/Cloudclub-istio-skyline#13]
**Question / 질문 내용**
https://jimmysong.io/en/blog/istio-pod-process-lifecycle/
위 링크에서 설명해주다시피 Sidecar auto-injection이 실행될 시 Init container가 먼저 실행되며 Pod에 traffic interception을 위해 iptables를 주입합니다. 

그러면 iptables에서 몇 계층까지 처리 되는지 궁금합니다.

<img src="https://jimmysong.io/en/blog/beyond-istio-oss/istio-route-iptables.svg" width="100%"/>
위 그림과 같이 iptables가 적용된 것 같은데 어떤 레이어 까지 들어가는지 확인이 안됩니다. 
<img src="https://qdnqn.com/content/images/2023/07/Netfilter-packet-flow.svg" width="100%"/>

**Context / 상황 설명**

**What I've Tried / 시도한 방법**
질문에 대한 답을 찾기 위해 시도해본 방법이 있다면 설명해주세요

아래 블로그를 보면 아마도 TCP인 듯 합니다. 다만 좀 시간이 지난 블로그인지라 명령어가 안 먹히네요
https://andrewpage.tistory.com/83

**Resources / 관련 자료**
질문과 관련된 문서, 링크, 코드 등이 있다면 여기에 첨부해주세요

**Additional context / 추가 사항**
기타 추가적인 정보나 생각이 있다면 여기에 작성해주세요

**Comment by ByeongHunKim** [comment]
오 두번째 사진은 직접 확인하실 때 캡쳐된 부분일까요? 어떻게 하셨는 지 궁금합니다.
