### ISSUE TITLE
[Season2] Milestone2 계획

### ISSUE THREAD

**Issue by ByeongHunKim** [ByeongHunKim/Cloudclub-istio-skyline#29]
# 요청사항
## 1. issue 등록되어있는 것 들 중에 아직 closed 안된 것들 있으면 이번주까지 진행해서 끝내주시면 될 것 같습니다
- 만약 마일스톤2 ( 스터디 시즌2 ) 에 이어서 할 내용이면 Label 추가해주시면 됩니다
<img width="1242" alt="image" src="https://github.com/user-attachments/assets/28413e9a-71a4-47af-852e-46c2afc2fc78">

---

## 2. 시즌2 진행할 때 이건 해봤으면 좋겠다는 내용이 있으면 의견 부탁드립니다!
- WIKI에 있는 내용 참고
<img width="927" alt="image" src="https://github.com/user-attachments/assets/891a5402-a40a-45a2-9073-deac269ea6a5">

**Comment by opp-13** [comment]
GCP를(Free Tier) TestBed 형식으로 상시 돌리는 것도 나쁘지 않을 듯 합니다.
