### ISSUE TITLE
[Question] Istio custom resource들이 어떻게 mesh logic으로 변하는가?

### ISSUE THREAD

**Issue by ByeongHunKim** [ByeongHunKim/Cloudclub-istio-skyline#3]
**Question / 질문 내용**

How Does Istio Send Configurations to Envoy Sidecars?

istiod가 istio 관련된 custom resources들 ( gateway, virtual Service, Destination Rule ) 들을 감지해서 envoy proxy가 이해할 수 있도록 mesh logic으로 변하게 하는 것으로 이해했는데 정확히 어떻게 변하는 지 제대로 이해는 못하였습니다.

**Context / 상황 설명**
<img width="685" alt="image" src="https://github.com/user-attachments/assets/63865f56-ee3d-4ced-a3b8-6e738a40e025">

위 영상을 보다가 mesh logic으로 변하는 부분

**What I've Tried / 시도한 방법**
질문에 대한 답을 찾기 위해 시도해본 방법이 있다면 설명해주세요

우선 이슈를 올려놓고 좀 알아볼 예정입니다.

**Resources / 관련 자료**
질문과 관련된 문서, 링크, 코드 등이 있다면 여기에 첨부해주세요

https://blog.naver.com/alice_k106/222000680202

https://www.zhaohuabing.com/post/2018-09-25-istio-traffic-management-impl-intro/#virtual-listener

**Additional context / 추가 사항**
기타 추가적인 정보나 생각이 있다면 여기에 작성해주세요

**Comment by opp-13** [comment]
도움이 될진 모르겠지만 관련 링크를 찾아서 공유해드립니다.

https://www.anyflow.net/sw-engineer/istio-internals-by-xds
https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol

**Comment by ByeongHunKim** [comment]
> 도움이 될진 모르겠지만 관련 링크를 찾아서 공유해드립니다.
> 
> https://www.anyflow.net/sw-engineer/istio-internals-by-xds https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol

**Comment by ByeongHunKim** [comment]
https://jimmysong.io/en/blog/istio-delta-xds-for-envoy/

**Comment by ByeongHunKim** [comment]
**Istio의 Custom Resource들이 mesh logic으로 변환된 이후 적용 순서가 어떻게 보장 되는지?** 

[istio-v1.23.1 코드] (https://github.com/istio/istio/blob/64cfafb98498c62fa35e981b95cb5c7a36678af8/pilot/pkg/model/push_context.go#L1275)

**Comment by ByeongHunKim** [comment]
1. [istio-v1.23.1 코드](https://github.com/istio/istio/blob/64cfafb98498c62fa35e981b95cb5c7a36678af8/pilot/pkg/model/push_context.go#L206) 의 pushContext 구조체에 정의된 것들이 k8s 환경의 모든 네임스페이스에 걸쳐 정의된 Istio CR들이 mesh logic으로 변환된 값들의 집합체인 것으로 이해함

2. [istio-v1.23.1 코드](https://github.com/istio/istio/blob/64cfafb98498c62fa35e981b95cb5c7a36678af8/pilot/pkg/model/push_context.go#L1275) 의 createNewContext() 함수 -> updateContext() 로 주기적으로 update하는 것으로 추정 중

**Comment by ByeongHunKim** [comment]
istiod는 xDS(CDS, EDS, LDS, RDS 등) 프로토콜을 통해 Envoy proxy에 설정을 동적으로 전달

cluster edge에 존재해서 트래픽을 받는 ingress gw pod도 proxy container 로 이루어져 있기 때문에 함께 동기화 되는 것 같음
```bash
k get pod <istio-ingressgateway-pod-name> -n istio-system -o jsonpath='{.spec.containers[*].name}'
# output 
# istio-proxy
```

**Comment by ByeongHunKim** [comment]
# [xDS 상세](https://www.anyflow.net/sw-engineer/istio-internals-by-xds#:~:text=arch_overview/operations/dynamic_configuration-,xDS%20%EC%83%81%EC%84%B8,-istioctl%20proxy%2Dconfig)

```bash
# 아래 명령어로 특정 파드의 Envoy 프록시 설정 중 라우트 정보를 YAML 형식으로 출력해서 확인할 수 있다
# 사이드카에 동기화된 모든 라우트 정보를 보여주는 것

istioctl proxy-config <clusters|listeners|routes|endpoints|bootstrap|log|secret> <pod-name[.namespace]> -o <short|yaml|json>
```

**Comment by ByeongHunKim** [comment]
> # [xDS 상세](https://www.anyflow.net/sw-engineer/istio-internals-by-xds#:~:text=arch_overview/operations/dynamic_configuration-,xDS%20%EC%83%81%EC%84%B8,-istioctl%20proxy%2Dconfig)
> ```shell
> # 아래 명령어로 특정 파드의 Envoy 프록시 설정 중 라우트 정보를 YAML 형식으로 출력해서 확인할 수 있다
> # 사이드카에 동기화된 모든 라우트 정보를 보여주는 것
> 
> istioctl proxy-config <clusters|listeners|routes|endpoints|bootstrap|log|secret> <pod-name[.namespace]> -o <short|yaml|json>
> ```

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/b0e10e30-fc46-4edb-8abf-06b522013161">

1. xDS란 - eXtensible Discovery Services의 약자로 dynamic configuration 관리 서버, 즉 istiod 가 노출하는 API 및 이들 서비스를 의미
2. Envoy는 istiod 를 ‘구독’하여 최종적 일관성(eventual consistency)에 기반하여 configuration을 상시 동기화한다
3. 동기화에는 Istio의 경우 gRPC를 사용함
4. xDS의 x에는 대표적으로 Listener(LDS), Route(RDS), Cluster(CDS), Endpoint(EDS)가 있는데, 이들 각각은 순서대로, Envoy가 노출할 port, 인입된 트래픽을 어떤 upstream 서비스로 보낼지 지정하는 규칙, upstream 서비스, 마지막으로 upstream 서비스의 주소를 가리킴

---

### Listener discovery service ( LDS )

### Route discovery service ( RDS )

### Cluster discovery service ( CDS )

### Endpoint discovery service ( EDS )

**Comment by ByeongHunKim** [comment]
이 issue는 `Cluster, Listener, Endpoint 등은 어떻게 등록할 수 있는가?` 로 봐도 될런지.. 모르겠네요

[블로그 글](https://cla9.tistory.com/191) 에서 등록하는 방식이 Static / Dynamic 으로 나뉘고, envoy proxy에서는 Static 등록 방식 이외에 Dynamic 방식을 제공하여 envoy proxy 기동 중에도 내부 컴포넌트 설정을 변경할 수 있도록 인터페이스를 제공하며 이를 xDS API라고 부른다고 하기 때문이에요

<img width="927" alt="image" src="https://github.com/user-attachments/assets/292d914d-f92d-45fb-88b5-35b83297ec10">

- 위와 같이 envoy의 주요 컴포넌트들을 알 수 있음

<img width="920" alt="image" src="https://github.com/user-attachments/assets/991a5384-8c44-4cb4-acf3-afacd4690d15">

- 위에서 설명한 주요 컴포넌트 Listener, Cluster, Endpoint를 갱신할 수 있는 Discovery Service가 제공되고 envoy proxy에서 요구하는 spec에 맞게 gRPC 혹은 REST 호출을 보내면 개별 컴포넌트에 해당하는 Discovery Service를 통해서 내부 컴포넌트 설정을 변경
- istio에서는 위와 같이 중앙에 envoy를 관리하는 Management Server가 있으며, Envoy의 xDS를 통해서 중앙에서 Configuration을 등록과 수정등을 자유롭게 할 수 있음

**Comment by ByeongHunKim** [comment]
# 직접 아래 명령어로 학습한 것을 바탕으로 테스트용 프로젝트의 envoy configuration들을 확인

```bash
istioctl proxy-config all production-5955b97cd7-ccj8s.istio-front > istio_proxy_config.txt
```

# Listener

```txt
NAME                         ADDRESSES      PORT  MATCH                                                                    DESTINATION
listener/172.20.13.94_3000   172.20.13.94   3000  Trans: raw_buffer; App: http/1.1,h2c                                     Route: production-auto-deploy.istio-front.svc.cluster.local:3000
listener/172.20.13.94_3000   172.20.13.94   3000  ALL                                                                      Cluster: outbound|3000||production-auto-deploy.istio-front.svc.cluster.local
listener/172.20.217.7_3000   172.20.217.7   3000  Trans: raw_buffer; App: http/1.1,h2c                                     Route: review-production-orddqb-auto-deploy.istio-front.svc.cluster.local:3000
listener/172.20.217.7_3000   172.20.217.7   3000  ALL                                                                      Cluster: outbound|3000||review-production-orddqb-auto-deploy.istio-front.svc.cluster.local
```


# Route

```txt
NAME                                                                                        VHOST NAME                                                                                  DOMAINS                                                                                              MATCH                  VIRTUAL SERVICE
route/production-auto-deploy.istio-front.svc.cluster.local:3000                             production-auto-deploy.istio-front.svc.cluster.local:3000                                   *                                                                                                    /* 
route/review-production-orddqb-auto-deploy.istio-front.svc.cluster.local:3000               review-production-orddqb-auto-deploy.istio-front.svc.cluster.local:3000                     *                                                                                                    /*                     
```

# Cluster

```txt
NAME                                                                                                          SERVICE FQDN                                                                           PORT      SUBSET         DIRECTION     TYPE             DESTINATION RULE
cluster/outbound|3000||production-auto-deploy.istio-front.svc.cluster.local                                   production-auto-deploy.istio-front.svc.cluster.local                                   3000      -              outbound      EDS              production-destination-rule.istio-front
cluster/outbound|3000|production|production-auto-deploy.istio-front.svc.cluster.local                         production-auto-deploy.istio-front.svc.cluster.local                                   3000      production     outbound      EDS              production-destination-rule.istio-front
cluster/outbound|3000||review-production-orddqb-auto-deploy.istio-front.svc.cluster.local                     review-production-orddqb-auto-deploy.istio-front.svc.cluster.local                     3000      -              outbound      EDS              review-prod-destination-rule.istio-front
cluster/outbound|3000|review|review-production-orddqb-auto-deploy.istio-front.svc.cluster.local               review-production-orddqb-auto-deploy.istio-front.svc.cluster.local                     3000      review         outbound      EDS              review-prod-destination-rule.istio-front
```

# Endpoint

```txt
NAME                                                      STATUS      LOCALITY                           CLUSTER
endpoint/10.1.59.255:3000                                 HEALTHY     ap-southeast-1/ap-southeast-1a     outbound|3000||production-auto-deploy.istio-front.svc.cluster.local
endpoint/10.1.59.255:3000                                 HEALTHY     ap-southeast-1/ap-southeast-1a     outbound|3000|production|production-auto-deploy.istio-front.svc.cluster.local
endpoint/10.1.54.168:3000                                 HEALTHY     ap-southeast-1/ap-southeast-1a     outbound|3000||review-production-orddqb-auto-deploy.istio-front.svc.cluster.local
endpoint/10.1.54.168:3000                                 HEALTHY     ap-southeast-1/ap-southeast-1a     outbound|3000|review|review-production-orddqb-auto-deploy.istio-front.svc.cluster.local
```
