### ISSUE TITLE
[Question] EKS에서 Istio 사용 시 ALB/NLB 선택 전략은?

### ISSUE THREAD

**Issue by opp-13** [ByeongHunKim/Cloudclub-istio-skyline#40]
**Question / 질문 내용**

EKS환경 내 istio 설치 시 LB 중 무엇을 사용하는 것이 좋은지 궁금합니다. 

**Context / 상황 설명**

현재 EKS 클러스터가 돌고 있고 LB가 설정이 되었는데 어떠한 LB가 Istio에 있어 적절한지 궁금합니다.

**What I've Tried / 시도한 방법**
질문에 대한 답을 찾기 위해 시도해본 방법이 있다면 설명해주세요

아래 자료를 통하여 일반적인 상황이라면 Istio와 ALB를 동시에 사용하는 것은 중복된 것이라고 이해했습니다.
https://tetrate.io/blog/ambient-mesh-what-you-need-to-know-about-this-experimental-new-deployment-model-for-istio/
https://stackoverflow.com/questions/57648680/nlb-istio-gateway-vs-alb-istio-gateway

다만 [이 링크의 제일 아래 답변](https://stackoverflow.com/questions/57648680/nlb-istio-gateway-vs-alb-istio-gateway)을 보면 아래 상황에서 ALB를 사용할 이유가 있다고 하는데 AWS 환경에서 자주 있는 상황인지 궁금합니다.
- WAF를 LB에 연동할 일이 있을 때
-  다른 pool의 EC2 instances로 traffic을 넘길 일이 있을 때 편리
- SSL offload를 하고 싶을 때
- NLB를 사용 시 보안 위협이 있다고 진단 될 때

**Resources / 관련 자료**
질문과 관련된 문서, 링크, 코드 등이 있다면 여기에 첨부해주세요

**Additional context / 추가 사항**
기타 추가적인 정보나 생각이 있다면 여기에 작성해주세요

ALB, NLB를 동시에 사용하는 것도 가능한 것 같아 살펴보고 있습니다.
https://nyyang.tistory.com/158

**Comment by opp-13** [comment]
비용적으로는 ALB보다는 NLB가 저렴하다고 확인했습니다.
ALB: LCU 시간(또는 부분 시간)당USD 0.008
NLB: NLCU 시간(또는 부분 시간)당 USD 0.006

https://aws.amazon.com/ko/elasticloadbalancing/pricing/

**Comment by ByeongHunKim** [comment]
@opp-13 

# 질문
- "Istio와 ALB를 동시에 사용하는 것은 중복된 것" 이라고 하신 부분이 이해가 잘 안가네요
   - ALB -> Istio Gateway 구성을 사용하고 있는게 중복이라면 어떻게 서비스를 외부로 노출시킬 수 있을까요?
- 다만, 내부 통신할 때 alb를 쓰는게 "추가적인 네트워크 홉으로 인한 latency 증가" 정도 그리고 가격적인 면도 있을 것 같긴하네요
- ALB -> Istio Gateway 구성이며, rate limiting을 istio에서 구현이 안되어있어서 AWS WAF 통합이 ALB에 되어있습니다
   - NLB+Istio Gateway로 했을 때 WAF와 통합이 안된다면 봇 같은 애들이 요청 보냈을 때 클러스터로는 모두 인입이 되는 것 아닐까요?
   - 그러면 istio-ingressgateway 가 무한정 scale out 될 것이고 ALB/ELB 요금을 아끼자고 하다가 노드 scale out이 되지 않을까 하는 생각이네요..

<img width="315" alt="image" src="https://github.com/user-attachments/assets/58a3d5e6-fc47-4715-be85-733c2db51d8d">


```
NAME                   REFERENCE                         TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
istio-ingressgateway   Deployment/istio-ingressgateway   54%/60%   10        100       25         157d
```

초당 2000정도 들어오면서 ingressgateway pod가 25개인 상황
- 그러면 여기에 envoy proxy container 하나 당 `"requests":{"cpu":"100m","memory":"128Mi"` 할당인데
- ELB + istio-ingressgateway로 한다면 진입점에서 못 막게되고 트래픽을 클러스터로 다 들여보낸다는 거 같아서요


# 결론
- ELB -> Istio Gateway를 사용해본 경우가 없네요..
   - ELB 로 단순 진입점 역할만 하게하면 좋을 것 같긴한데 istio에서 모두 구현하고 운영하고 할 수 있을지도 모르겠어요
- "Istio와 ALB를 동시에 사용하는 것은 중복된 것" 이라는 내용이 이해가 안가네요

# reference
## [ALB vs ELB](https://velog.io/@vanillacake369/AWS-ELB-ALB-vs-NLB)

**Comment by opp-13** [comment]
@ByeongHunKim
Istio와 ALB를 동시에 사용하는 것은 중복된 것 => 정확히 말하자면 하는 일이 중복되어 필요 없을 것 같다는 말이였습니다.

**Comment by ByeongHunKim** [comment]
> @ByeongHunKim Istio와 ALB를 동시에 사용하는 것은 중복된 것 => 정확히 말하자면 하는 일이 중복되어 필요 없을 것 같다는 말이였습니다.

말씀하신게 맞긴 한데.. 제가 봤을 때  NLB + istio-ingressgateway 조합으로 했을 때의 이점보다 ALB + ingressgateway 이점이 더 큰거 같네요. WAF가 필요한 상황에서는 이 중복이 불가피한 선택일 수 밖에 없고요. 하지만 @opp-13 님 말대로 중복되는 것 같긴하네요. 저도 다른 큰 회사들 같은 곳들은 어떻게 쓰는 지 알고싶습니다.

1. 비용 : 아낄 순 있지만 가격차이가 뭐 2배나는 건 아닌 것 같기 때문
2. 성능 : 낮은 지연시간 제공하긴 하겠지만 istio로 모든 L7 관련된 작업을 처리하기엔 아직 경험이 없기 때문
   - 이 작업을 하다가 시스템을 비정상 상태로 만들면.. 더 큰 참사

**Comment by ByeongHunKim** [comment]
@opp-13 추가적인 이야기

# 내부통신을 구현했을 때와 아닐 때 차이
- private subnet에 worker node, NAT GW 배치 되어있는 상황

## 1. 내부 통신이 아닐 때

### 1.1 백엔드 파드의 istio-proxy의 요청 로그 중 x-forwared-for header에 있는 source ip
- 아래 ip들은 각 AZ별 배치되어있는 NAT GW의 EIP 리스트 ( NatGatewayEIP 1~3 )
- 이때 프론트에서 호출하는 endpoint URL이 Route53 public hosting zone A 레코드의 alias 별칭으로 public ALB로 매핑되어있음
- 그래서 외부 요청 -> alb -> istio-ingressgateway -> front pod ( istio-proxy ) -> 외부로 나감 ( NAT GW 통해서 ) -> 다시 클러스터 내부로 들어옴 -> istio-ingressgateway -> backend pod ( istio-proxy ) 에 찍히는 ip는 NAT EIP로 변환한 IP 임
```bash
‘x-forwarded-for’, ‘18.xxx.xxx.52,....’
‘x-forwarded-for’, ‘3.1.xxx.xxx,....’
‘x-forwarded-for’, ‘52.xxx.xxx.136,....’
```

## 2. 내부 통신 처리를 했을 때

### 2.1 백엔드 파드의 istio-proxy의 요청 로그 중 x-forwared-for header에 있는 source ip
- 아래 ip들은 각 AZ별 배치되어있는 private subnet 에 위치한 internal alb의 IP들
- 이때 프론트에서 호출하는 endpoint URL이 Route53 private hosting zone A 레코드의 alias 별칭으로 internal ALB로 매핑되어있음
- 그래서 외부 요청 -> alb -> istio-ingressgateway -> front pod ( istio-proxy ) -> 외부로 나가지 않음  -> backend pod ( istio-proxy ) 로 바로 들어옴. 이 둘 간의 istio-proxy ( service mesh ) 통신으로 보여짐
```bash
# 예시
k get po -n <frontend> -o wide
# production-756d88c589-pddrw                 2/2     Running                  0          25m     10.1.48.190
```

![image (13)](https://github.com/user-attachments/assets/315f67a9-9b56-44a5-8882-f9955ace5f51)
- 10.1.48.190 이 ip가 백엔드 istio-proxy에서 찍히는 것은 외부로 나가서 NAT가 ip를 바꾸지 않고 istio-proxy들 간의 통신이 이루어졌다고 봄
